<?php

/**
 * Created by PhpStorm.
 * User: root
 * Date: 10.04.18
 * Time: 23:21
 */
namespace app\components;
use yii\base\Widget;

class MyWidget extends Widget
{
public $name;
    function run(){
     //   return $this->name.', hello World! From widget ';
    //return $this->render('my.php', ['name'=>'Petya']);
        $content = ob_get_clean();
        $content = mb_strtoupper($content);
        return $this->render('my',compact('content'));

    }

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();

        //if ($this->name === null) $this->name="Guest";

    }

}