<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 03.04.18
 * Time: 22:48
 */

namespace app\models;


use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public static function tableName()
    {
        return 'products'; // TODO: Change the autogenerated stub
    }

    public function getCategory(){
        return $this->hasOne(Category::className(),['id'=>'parent']);
    }

}